AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - features/**/*
    - vendor/**/*

Layout/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: mixed

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/LineLength:
  Max: 120
